image: docksal/bitbucket-pipelines-agent:1.0

pipelines:
  default:
    - step:
        script:
          - source build-env  # Initialize the agent configuration
          - build-init  # Initialize the remote sandbox environment
          - slack "Started sandbox build for branch *${BITBUCKET_BRANCH}*"  # post to Slack
          - ssh docker-host "cd $REMOTE_BUILD_DIR && fin init"  # Run fin init on the remote docker host to provision a sandbox
          - slack "Completed sandbox build for branch *${BITBUCKET_BRANCH}*:\n<http://${DOMAIN}|http://${DOMAIN}>"
